### PR TITLE
Bump version: 2020.04.0 → 2020.05.0

### PR DESCRIPTION
**Pull request by palango**
~~⚠️ Merge only after it's decided if https://github.com/raiden-network/raiden-service-bundle/pull/153 should be merged or not.~~

### CODE REVIEW

**Comment by fredo** [comment]
Here we would also need the docker-compose.yml to be updated

**Comment by fredo** [comment]
which would then mean that PR #153 is outdated

**Comment by palango** [comment]
So we want `image: raidennetwork/raiden-service-bundle:2020.05.0-db`? Then we have a cyclic problem, right?

**Comment by ulope** [comment]
Yes the tag in the referenced image should point to the not yet existing "future" tag that is being built with the same PR.

Since nobody is supposed to use `master` but only tagged releases this shouldn't cause any issues.

**Pull request merged**
